import { serializeFields, validateFieldsClient } from './fields';
import type { FormState, ScrapeBody } from './types';

const AUTO_OUTPUT_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*-\d{14}\.csv$/;

export function slugifyPresetName(presetName: string): string {
  const slug = String(presetName || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || 'list';
}

export function compactTimestamp(date = new Date()): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;
}

export function suggestedOutputName(presetName = '', date = new Date()): string {
  return `${slugifyPresetName(presetName)}-${compactTimestamp(date)}.csv`;
}

export function isAutoGeneratedOutput(value: unknown): boolean {
  const v = String(value || '').trim();
  return v === '' || AUTO_OUTPUT_RE.test(v);
}

export function normalizeOutputForForm(value: unknown): string {
  return isAutoGeneratedOutput(value) ? '' : String(value || '').trim();
}

export function validateUrlClient(url: string): string | null {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return 'Please enter a valid URL.';
  }
  if (!['http:', 'https:'].includes(parsed.protocol)) {
    return 'URL must use http or https.';
  }
  return null;
}

function optionalNonNegativeInt(raw: string, label: string): string | null {
  if (raw === '') return null;
  const n = Number(raw);
  if (!Number.isInteger(n) || n < 0) {
    return `${label} must be a non-negative integer.`;
  }
  return null;
}

export function validateForm(form: FormState): string | null {
  if (!form.url.trim()) return 'Please enter a starting page URL.';
  const urlErr = validateUrlClient(form.url.trim());
  if (urlErr) return urlErr;
  if (!form.container.trim()) return 'Container selector is required.';
  if (!form.item.trim()) return 'Item selector is required.';
  const fieldsErr = validateFieldsClient(serializeFields(form.fields));
  if (fieldsErr) return fieldsErr;
  if (form.paginate && form.strategy !== 'next-link' && form.strategy !== 'url-pattern') {
    return 'Choose a pagination strategy.';
  }
  if (form.paginate && form.strategy === 'next-link' && !form.nextSelector.trim()) {
    return '"Next page" selector is required.';
  }
  if (form.paginate && form.strategy === 'url-pattern' && !form.urlTemplate.includes('{page}')) {
    return 'URL template must contain {page}.';
  }
  return (
    optionalNonNegativeInt(form.retryAttempts.trim(), 'Retries') ||
    optionalNonNegativeInt(form.retryDelayMs.trim(), 'Retry delay') ||
    optionalNonNegativeInt(form.pageDelayMs.trim(), 'Page delay')
  );
}

export function toScrapeBody(form: FormState): ScrapeBody {
  const body: ScrapeBody = {
    url: form.url.trim(),
    container: form.container.trim(),
    item: form.item.trim(),
    fields: serializeFields(form.fields),
    output: form.output.trim(),
    paginate: form.paginate,
    strategy: form.strategy,
    nextSelector: form.nextSelector.trim(),
    nextUrlSourceSelector: form.nextUrlSourceSelector.trim(),
    nextUrlAttribute: form.nextUrlAttribute.trim(),
    nextSiblingSelector: form.nextSiblingSelector.trim(),
    urlTemplate: form.urlTemplate.trim(),
    maxPages: Number(form.maxPages) || 0,
    failOnPageError: form.failOnPageError,
  };
  if (form.retryAttempts.trim() !== '') body.retryAttempts = Number(form.retryAttempts);
  if (form.retryDelayMs.trim() !== '') body.retryDelayMs = Number(form.retryDelayMs);
  if (form.pageDelayMs.trim() !== '') body.pageDelayMs = Number(form.pageDelayMs);
  if (!body.output) delete body.output;
  return body;
}
